### ISSUE TITLE
What does blogFeedback.py code mean ?

### ISSUE THREAD

**Issue by Mohammed-Elias** [rupakc/UCI-Data-Analysis#1]
First things first, thank you so much for this amazing repo.

I wanted to use the data in `Blog_Feedback` folder, then I saw the code, but I didn't know what does it mean, excuse me, I'm so new on the Machine learning field.

So could you please, clarify it to me ?

Thanks in advance.

**Comment by rupakc** [comment]
The BlogFeedback folder contains the data for this dataset -
http://archive.ics.uci.edu/ml/datasets/BlogFeedback

The code trains several regression models on the BlogFeedback dataset (link given above) and evaluates the performance.
